"""add staff_services table

Revision ID: 17269583f8bc
Revises: 17c2e6b3dd2b
Create Date: 2026-03-10 00:39:04.592231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17269583f8bc'
down_revision: Union[str, None] = '17c2e6b3dd2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('beauty_service_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['beauty_service_id'], ['beauty_services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_services_beauty_service_id'), 'staff_services', ['beauty_service_id'], unique=False)
    op.create_index(op.f('ix_staff_services_staff_id'), 'staff_services', ['staff_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_services_staff_id'), table_name='staff_services')
    op.drop_index(op.f('ix_staff_services_beauty_service_id'), table_name='staff_services')
    op.drop_table('staff_services')
    # ### end Alembic commands ###
