"""add beauty_bookings table

Revision ID: 903029bfcfa8
Revises: 957c454df7d5
Create Date: 2026-03-10 19:17:58.625897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '903029bfcfa8'
down_revision: Union[str, None] = '957c454df7d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beauty_bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('beauty_service_id', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='confirmed', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['beauty_service_id'], ['beauty_services.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beauty_bookings_beauty_service_id'), 'beauty_bookings', ['beauty_service_id'], unique=False)
    op.create_index(op.f('ix_beauty_bookings_end_datetime'), 'beauty_bookings', ['end_datetime'], unique=False)
    op.create_index('ix_beauty_bookings_staff_end', 'beauty_bookings', ['staff_id', 'end_datetime'], unique=False)
    op.create_index(op.f('ix_beauty_bookings_staff_id'), 'beauty_bookings', ['staff_id'], unique=False)
    op.create_index('ix_beauty_bookings_staff_start', 'beauty_bookings', ['staff_id', 'start_datetime'], unique=False)
    op.create_index(op.f('ix_beauty_bookings_start_datetime'), 'beauty_bookings', ['start_datetime'], unique=False)
    op.create_index(op.f('ix_beauty_bookings_status'), 'beauty_bookings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_beauty_bookings_status'), table_name='beauty_bookings')
    op.drop_index(op.f('ix_beauty_bookings_start_datetime'), table_name='beauty_bookings')
    op.drop_index('ix_beauty_bookings_staff_start', table_name='beauty_bookings')
    op.drop_index(op.f('ix_beauty_bookings_staff_id'), table_name='beauty_bookings')
    op.drop_index('ix_beauty_bookings_staff_end', table_name='beauty_bookings')
    op.drop_index(op.f('ix_beauty_bookings_end_datetime'), table_name='beauty_bookings')
    op.drop_index(op.f('ix_beauty_bookings_beauty_service_id'), table_name='beauty_bookings')
    op.drop_table('beauty_bookings')
    # ### end Alembic commands ###
