"""add staff availability rules

Revision ID: 957c454df7d5
Revises: 17269583f8bc
Create Date: 2026-03-10 01:57:55.584621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957c454df7d5'
down_revision: Union[str, None] = '17269583f8bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_availability_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_availability_rules_id'), 'staff_availability_rules', ['id'], unique=False)
    op.create_index(op.f('ix_staff_availability_rules_staff_id'), 'staff_availability_rules', ['staff_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_availability_rules_staff_id'), table_name='staff_availability_rules')
    op.drop_index(op.f('ix_staff_availability_rules_id'), table_name='staff_availability_rules')
    op.drop_table('staff_availability_rules')
    # ### end Alembic commands ###
