"""add bookings table

Revision ID: b3c09d841375
Revises: e84d040269b2
Create Date: 2026-03-09 18:24:02.825022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c09d841375'
down_revision: Union[str, None] = 'e84d040269b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('barber_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='confirmed', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['barber_id'], ['barbers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bookings_barber_end', 'bookings', ['barber_id', 'end_datetime'], unique=False)
    op.create_index(op.f('ix_bookings_barber_id'), 'bookings', ['barber_id'], unique=False)
    op.create_index('ix_bookings_barber_start', 'bookings', ['barber_id', 'start_datetime'], unique=False)
    op.create_index(op.f('ix_bookings_end_datetime'), 'bookings', ['end_datetime'], unique=False)
    op.create_index(op.f('ix_bookings_service_id'), 'bookings', ['service_id'], unique=False)
    op.create_index(op.f('ix_bookings_start_datetime'), 'bookings', ['start_datetime'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_start_datetime'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_service_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_end_datetime'), table_name='bookings')
    op.drop_index('ix_bookings_barber_start', table_name='bookings')
    op.drop_index(op.f('ix_bookings_barber_id'), table_name='bookings')
    op.drop_index('ix_bookings_barber_end', table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
