"""add barber availability rules

Revision ID: e84d040269b2
Revises: f7ec8b544514
Create Date: 2026-02-06 23:49:03.533833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e84d040269b2'
down_revision: Union[str, None] = 'f7ec8b544514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barber_availability_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barber_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['barber_id'], ['barbers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barber_availability_rules_barber_id'), 'barber_availability_rules', ['barber_id'], unique=False)
    op.create_index(op.f('ix_barber_availability_rules_day_of_week'), 'barber_availability_rules', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_barber_availability_rules_id'), 'barber_availability_rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_barber_availability_rules_id'), table_name='barber_availability_rules')
    op.drop_index(op.f('ix_barber_availability_rules_day_of_week'), table_name='barber_availability_rules')
    op.drop_index(op.f('ix_barber_availability_rules_barber_id'), table_name='barber_availability_rules')
    op.drop_table('barber_availability_rules')
    # ### end Alembic commands ###
